using System.Diagnostics.CodeAnalysis;

// This analyzer is currently broken: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3370
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1119:Statement should not use unnecessary parenthesis")]

// TODO: remove this once parameter null checks and CallerArgumentExpression are released
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules",          "SA1503:Braces should not be omitted")]

// TODO: keep these suppressed but temporarily unsuppress to clean code
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules",     "SA1107:Code should not contain multiple statements on one line")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules",         "SA1025:Code should not contain multiple whitespace in a row")]

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules",   "SA1600:Elements should be documented")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules",   "SA1623:Property summary documentation should match accessors")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules",   "SA1629:Documentation text should end with a period")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules",   "SA1633:File should have header")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules",   "SA1642:Constructor summary documentation should begin with standard text")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules",   "SA1649:File name should match first type name")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules",          "SA1500:Braces for multi-line statements should not share line")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules",          "SA1502:Element should not be on a single line")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules",          "SA1505:Opening braces should not be followed by blank line")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules",          "SA1508:Closing braces should not be preceded by blank line")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules",          "SA1509:Opening braces should not be preceded by blank line")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules",          "SA1512:Single-line comments should not be followed by blank line")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules",          "SA1513:Closing brace should be followed by blank line")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules",          "SA1514:Element documentation header should be preceded by blank line")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules",          "SA1515:Single-line comment should be preceded by blank line")]
[assembly: SuppressMessage("StyleCop.CSharp.LayoutRules",          "SA1516:Elements should be separated by blank line")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1401:Fields should be private")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single type")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1404:Code analysis suppression should have justification")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1407:Arithmetic expressions should declare precedence")]
[assembly: SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1408:Conditional expressions should declare precedence")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules",          "SA1300:Element should begin with upper-case letter")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules",          "SA1303:Const field names should begin with upper-case letter")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules",          "SA1304:Non-private readonly fields should begin with upper-case letter")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules",          "SA1306:Field names should begin with lower-case letter")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules",          "SA1307:Accessible fields should begin with upper-case letter")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules",          "SA1309:Field names should not begin with underscore")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules",          "SA1310:Field names should not contain underscore")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules",          "SA1311:Static readonly fields should begin with upper-case letter")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules",          "SA1312:Variable names should begin with lower-case letter")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules",          "SA1313:Parameter names should begin with lower-case letter")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules",        "SA1200:Using directives should be placed correctly")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules",        "SA1201:Elements should appear in the correct order")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules",        "SA1202:Elements should be ordered by access")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules",        "SA1203:Constants should appear before fields")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules",        "SA1204:Static elements should appear before instance elements")]
[assembly: SuppressMessage("StyleCop.CSharp.OrderingRules",        "SA1214:Readonly fields should appear before non-readonly fields")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules",     "SA1101:Prefix local calls with this")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules",     "SA1108:Block statements should not contain embedded comments")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules",     "SA1111:Closing parenthesis should be on line of last parameter")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules",     "SA1116:Split parameters should start on line after declaration")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules",     "SA1117:Parameters should be on same line or separate lines")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules",     "SA1118:Parameter should not span multiple lines")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules",     "SA1123:Do not place regions within elements")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules",     "SA1124:Do not use regions")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules",     "SA1127:Generic type constraints should be on their own line")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules",     "SA1128:Put constructor initializers on their own line")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules",     "SA1131:Use readable conditions")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules",     "SA1413:Use trailing comma in multi-line initializers")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules",         "SA1000:Keywords should be spaced correctly")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules",         "SA1008:Opening parenthesis should be spaced correctly")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules",         "SA1009:Closing parenthesis should be spaced correctly")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules",         "SA1011:Closing square brackets should be spaced correctly")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules",         "SA1027:Use tabs correctly")]

// specific to testing
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules",         "SA1021:Negative signs should be spaced correctly")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules",     "SA1122:Use string.Empty for empty strings")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules",   "SA1601:Partial elements should be documented")]
